### ISSUE TITLE
write to matrix over monoid incorrect

### ISSUE THREAD

**Issue by timjbaer** [cyclops-community/ctf#91]
Write to matrix defined on monoid is returning incorrect results (at least when writing to the diagonal). Returns the correct result when defined over a semiring.

The following is a minimal example:

```
/* 
 * Demonstrates bug when trying to "zero" diagonal of matrix.
 * Matrix must be defined over a semiring for write to work correctly.
 * If the matrix defined over a monoid, A["ii"] = Scalar<int>[""] and A["ii"] = Vector<int>["i"] returns incorrect result.
 */
#include <ctf.hpp>

using namespace CTF;

int main(int argc, char **argv)
{
  int rank;
  int np;
  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  MPI_Comm_size(MPI_COMM_WORLD, &np);
  auto w = new World(argc, argv);

  Scalar<int> addid(5);

  int n = 2;
  int64_t npair = 4;
  Pair<int> * pairs = new Pair<int>[npair];
  pairs[0] = Pair<int>(0 * n + 0, 10);
  pairs[1] = Pair<int>(0 * n + 1, 10);
  pairs[2] = Pair<int>(1 * n + 0, 10);
  pairs[3] = Pair<int>(1 * n + 1, 10);

  {
    Matrix<int> * A = new Matrix<int>(n, n, SP, *w, Monoid<int>());
    A->write(npair, pairs);

    (*A)["ii"] = addid[""];
    printf("write over monoid with scalar\n");
    A->print();

    delete A;
  }

  {
    Matrix<int> * A = new Matrix<int>(n, n, SP, *w, Monoid<int>());
    A->write(npair, pairs);

    Vector<int> vaddid(n, *w, Semiring<int>());
    vaddid["i"] = addid[""];
    (*A)["ii"] = vaddid["i"];
    printf("write over monoid with vector\n");
    A->print();

    delete A;
  }

  {
    Matrix<int> * A = new Matrix<int>(n, n, SP, *w, Semiring<int>());
    A->write(npair, pairs);

    (*A)["ii"] = addid[""];
    printf("write over sr\n");
    A->print();
    
    delete A;
  }
  delete [] pairs;

  return 0;
}
```

With output:
```
write over monoid with scalar
Printing tensor ETXS02
Tensor has 2 nonzeros
[0][0](0, <5>)
[1][1](3, <5>)
write over monoid with vector
Printing tensor AILI02
Tensor has 2 nonzeros
[0][0](0, <5>)
[1][1](3, <5>)
write over sr
Printing tensor AQYJ02
Tensor has 4 nonzeros
[0][0](0, <5>)
[1][0](1, <10>)
[0][1](2, <10>)
[1][1](3, <5>)
```

**Comment by solomonik** [comment]
@timjbaer thanks for reporting this and for the test to reproduce it. Commit 36b1f6d should cause CTF to throw an error for such cases, but I think there is actually some technical justification for CTF not to support this functionality. Generally a CTF summation performs `B = beta*B + alpha*A` provided that A and B have multiplicative operators (are defined over a semiring). If they are defined over the monoid, a CTF summation will perform `B = B + A`. When executing a summation like `B["..."]=A["..."]`, where B is over a monoid, CTF was previously setting B to zero via `B.set_zero()` then performing`B["..."]+=A["..."]`, which is a valid CTF summation operation. However, if an output index is repeated, i.e., we want to do B["...i...i..."]=A["..."]` this method is incorrect. So we would need a work around such as implementing a set_zero function that iterates over the diagonals of tensors, which is possible, but there is also a simple user-end workaround of defining a Semiring rather than a Monoid with a simple multiplicative operator that only works when one operand is an additive identity element, so that CTF can perform beta*B for beta=0. So, will not try to fix this unless issues with the workaround arise.
